export const DEFAULT_TRAININGPEAKS_CONTACT = "/contato-trainingpeaks"; 

const plans = [
  // Base
  {
    name: 'Plano Branco',
    nivel: 'iniciante',
    coach: 'Jack Daniels',
    info: 'Desenvolva uma base sólida de corrida com o método comprovado de Jack Daniels. Este plano de 16 semanas é ideal para Iniciantes, focando no aumento gradual do volume e na construção de consistência. Prepare-se para descobrir o prazer da corrida e melhorar seu condicionamento geral.',
    path: 'jack-daniels-iniciante',
    duration: '16 semanas',
    activities: ['corrida'],
    img: '/img/pages/shared.jpg',
    isNew: false,
    distances: ['5km'],
    trainingPeaksUrl: 'https://www.trainingpeaks.com/my-training-plans/iniciante',
    volume: '20'
  },
  {
    name: 'Faster Road Racing: Base 1',
    nivel: 'iniciante',
    coach: 'Pete Pfitzinger',
    info: 'Plano de 10 semanas para construir uma base aeróbica sólida, desenvolvido por Pete Pfitzinger e Philip Latter. Ideal para corredores iniciantes a intermediários que buscam aumentar seu volume semanal até 50 km. Inclui corridas fáceis, treinos de limiar e intervalados, preparando o corredor para distâncias de 5 km a meia maratona.',
    path: 'frr-treino-base-1',
    duration: '10 semanas',
    activities: ['corrida'],
    img: '/img/pages/shared.jpg',
    isNew: true,
    distances: ['5km', '10km', '21km'],
    volume: '50'
  },

  {
    name: 'Plano Vermelho',
    nivel: 'intermediário',
    coach: 'Jack Daniels',
    info: 'Eleve seu treinamento com o Plano Vermelho de Jack Daniels. Projetado para corredores intermediários, este programa de 16 semanas incorpora variedade de ritmos e intensidades. Aprimore sua resistência, velocidade e eficiência para alcançar novos patamares de desempenho.',
    path: 'jack-daniels-plano-vermelho',
    duration: '16 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: false,
    distances: ['5km', '10km'],
    volume: '60',
    trainingPeaksUrl: 'https://www.trainingpeaks.com/training-plans/running/5km/tp-539722/fundamentos-da-corrida-intermediario',
  },
  {
    name: 'Faster Road Racing: Base 2',
    nivel: 'intermediário',
    coach: 'Pete Pfitzinger',
    info: 'Este plano de 10 semanas, desenvolvido por Pete Pfitzinger e Philip Latter, é projetado para construir uma base sólida de corrida, aumentando gradualmente o volume até 75 km por semana. Ideal para corredores intermediários que buscam melhorar sua resistência e preparar-se para treinos mais específicos de corrida. O plano inclui uma variedade de treinos, incluindo corridas longas, treinos de ritmo de limiar e tiros de velocidade.',
    path: 'frr-treino-base-2',
    duration: '10 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['5km', '10km', '21km'],
    volume: '75'
  },
  {
    name: 'Plano Azul',
    nivel: 'avançado',
    coach: 'Jack Daniels',
    info: 'Desafie-se com o Plano Azul avançado de Jack Daniels. Este programa intensivo de 16 semanas é voltado para corredores experientes, incorporando treinos de alta qualidade e volume substancial. Explore seus limites e otimize seu potencial atlético com métodos cientificamente comprovados.',
    path: 'jack-daniels-plano-azul',
    duration: '16 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: false,
    distances: ['5km', '10km']
  },
  {
    name: 'Faster Road Racing: Base 3',
    nivel: 'avançado',
    coach: 'Pete Pfitzinger',
    info: 'Plano de 10 semanas para construção de base, com volume semanal de até 100 km. Desenvolvido por Pete Pfitzinger e Philip Latter, este programa é ideal para corredores avançados que buscam aumentar seu volume semanal de forma gradual e segura. Inclui uma variedade de treinos, como corridas longas, treinos de ritmo de limiar e treinos de velocidade. Extraído do livro "Faster Road Racing: 5K to Half Marathon".',
    path: 'frr-treino-base-3',
    duration: '10 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    isStar: true,
    distances: ['5km', '10km', '21km'],
    volume: '100'
  },
  {
    name: 'Plano Dourado',
    nivel: 'elite',
    coach: 'Jack Daniels',
    info: 'O Plano Dourado é um programa de elite de 16 semanas desenvolvido por Jack Daniels para atletas avançados que buscam alto desempenho em várias distâncias. Com um volume semanal entre 96-120 km, este plano exigente incorpora uma variedade de intensidades e é ideal para corredores experientes que treinam 6-7 dias por semana, incluindo alguns dias com treinos duplos.',
    path: 'jack-daniels-plano-dourado',
    duration: '16 semanas',
    activities: ['corrida'],
    img: '/img/planos/jack-daniels-plano-dourado.jpg',
    isNew: true,
    distances: ['5km', '10km', '21km', '42km'],
    volume: '120'
  },
  // 5K Plans
  {
    name: '5 Km Hal Higdon',
    nivel: 'iniciante',
    coach: 'Hal Higdon',
    info: 'Inicie sua jornada na corrida com o plano de 5 km de Hal Higdon. Este programa de 8 semanas é perfeito para Iniciantes, combinando corridas curtas com caminhadas. Construa resistência gradualmente e prepare-se para completar sua primeira prova de 5 km com confiança.',
    path: '5km-halhigdon-iniciante',
    duration: '08 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['5km']
  },
  {
    name: "Runner's Blueprint Couch 5 km",
    nivel: "iniciante",
    coach: "Runner's Blueprint",
    info: "Este popular plano de 8 semanas da Runner's Blueprint é projetado para transformar sedentários em corredores de 5 km. Começando com uma mistura de caminhada e corrida, o programa aumenta gradualmente a duração dos intervalos de corrida, permitindo que o corpo se adapte de forma segura e eficaz. Ideal para iniciantes absolutos ou para quem está retornando à corrida após um longo período de inatividade.",
    path: "5km-blueprint-iniciante",
    duration: "8 semanas",
    img: "/img/pages/shared.jpg",
    activities: ["corrida"],
    isNew: true,
    distances: ["5km"],
    volume: "30"
  },
  {
    name: 'Nike Run Club 5 Km',
    nivel: 'iniciante',
    coach: 'Chris Bennett',
    info: 'Prepare-se para sua primeira corrida de 5 km com este plano de 8 semanas da Nike Run Club. Desenvolvido por Chris Bennett, este programa combina corridas fáceis, treinos de velocidade e corridas longas para construir sua resistência e confiança. Ideal para corredores iniciantes ou aqueles que buscam melhorar seu tempo nos 5 km.',
    path: '5km-nike-iniciante',
    duration: '08 semanas',
    img: '/img/planos/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['5km']
  },
  {
    name: 'Do Sofá aos 5 Km',
    nivel: 'iniciante',
    coach: 'Comunidade',
    info: 'O plano Do Sofá aos 5 Km (Couch to 5K) é um programa de 8 semanas, projetado para transformar sedentários em corredores de 5K. Combina caminhada e corrida de forma progressiva, permitindo que o corpo se adapte gradualmente ao exercício. Ideal para quem está começando do zero ou retornando após longo período sem atividade física.',
    path: '5km-couch-iniciante',
    duration: '08 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['5km']
  },
  {
    name: '5 Km Trail REI',
    nivel: 'iniciante',
    coach: 'REI',
    info: 'Este plano de 6 semanas é projetado para preparar corredores iniciantes para uma corrida de trail de 5 km. Combina treinamento em colinas, corridas de tempo, treinos fáceis e corridas longas para desenvolver força, resistência e habilidades específicas para trilhas. Ideal para quem busca experimentar o desafio e a aventura das corridas off-road.',
    path: '5km-rei-iniciante',
    duration: '06 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida', 'trail'],
    isNew: true,
    distances: ['5km'],
    volume: '40'
  },
  {
    name: '5 Km - Hal Higdon',
    nivel: 'intermediário',
    coach: 'Hal Higdon',
    info: 'Aprimore seu tempo nos 5 km com o plano intermediário de Hal Higdon. Este programa de 8 semanas inclui treinos variados como intervalos e corridas de ritmo. Ideal para corredores que já completaram 5 km e buscam melhorar seu desempenho.',
    path: '5km-halhigdon-intermediario',
    duration: '08 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: false,
    distances: ['5km', '10km']
  },
  {
    name: '5 km - Faster Road Racing',
    nivel: 'intermediário',
    coach: 'Pete Pfitzinger',
    info: 'Alcance seu melhor desempenho nos 5 km com o plano avançado de Pete Pfitzinger e Philip Latter. Este programa de 12 semanas combina ciência e experiência prática, focando em treinos de alta qualidade e periodização eficiente para otimizar sua velocidade e resistência.',
    path: '5km-frr-intermediario',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: false,
    distances: ['5km', '10km'],
    volume: '50'
  },
  {
    name: '5 Km Pete Magill',
    nivel: 'avançado',
    coach: 'Pete Magill',
    info: 'Plano de treinamento de 5km baseado no método de Pete Magill, focado em corredores intermediários que buscam melhorar seu tempo. Combina corridas fáceis, treinos de colinas, intervalos e corridas longas para um desenvolvimento completo ao longo de 12 semanas.',
    path: '5km-pete-magill-avancado',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['5km', '10km']
  },
  {
    name: '5 Km Hal Higdon',
    nivel: 'avançado',
    coach: 'Hal Higdon',
    info: 'Maximize seu potencial nos 5 km com o plano avançado de Hal Higdon. Este programa intensivo de 8 semanas é projetado para corredores experientes visando tempos competitivos. Inclui treinos de alta intensidade e volume para impulsionar velocidade e resistência.',
    path: '5km-halhigdon-avancado',
    duration: '08 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['5km', '10km']
  },
  {
    name: '5 km - Faster Road Racing',
    nivel: 'avançado',
    coach: 'Pete Pfitzinger',
    info: 'Este plano de 12 semanas, desenvolvido por Pete Pfitzinger e Philip Latter, é projetado para corredores avançados que buscam melhorar seu desempenho em provas de 5 km. O programa começa com um volume semanal de cerca de 70 km e aumenta gradualmente até cerca de 85 km. Inclui uma variedade de treinos, como corridas longas, treinos de ritmo de limiar, intervalos de VO2 max e corridas de recuperação. Ideal para corredores que já têm uma base sólida e querem levar seu desempenho para o próximo nível.',
    path: '5km-frr-avancado',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['5km', '10km'],
    volume: '70'
  },
  {
    name: '5 km - Ingebrigtsen',
    nivel: 'elite',
    coach: 'Gjert Ingebrigtsen',
    info: 'O método de treinamento dos irmãos Ingebrigtsen, criado pelo pai deles, Gjert, foca em volume 180-200 km/semana, intervalos longos, treinos intensivos e recuperação ativa. Inclui também treinamento em altitude, progressão gradual, especificidade para as distâncias alvo, consistência e trabalho de força. Esse regime rigoroso é ajustado às necessidades dos irmãos, mas pode não ser adequado para todos os atletas. 👽🚷',
    path: '5km-ingebrigtsen',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['5km', '10km']
  },
  {
    name: '5 km - Faster Road Racing',
    nivel: 'elite',
    coach: 'Pete Pfitzinger',
    info: 'Este plano de 12 semanas, desenvolvido por Pete Pfitzinger e Philip Latter, é projetado para corredores avançados que buscam melhorar seu desempenho em provas de 5 km até 10 km. O programa começa com um volume semanal de cerca de 80 km e aumenta gradualmente até cerca de 100 km. Inclui uma variedade de treinos, como corridas longas, treinos de ritmo de limiar, intervalos de VO2 max e corridas de recuperação. Ideal para corredores que já têm uma base sólida e querem levar seu desempenho para o próximo nível.',
    path: '5km-frr-elite',
    duration: '12 semanas',
    activities: ['corrida'],
    img: '/img/pages/shared.jpg',
    isNew: true,
    distances: ['5km', '10km', '15km'],
    volume: '100'
  },
  // 5K/10K Plans
  {
    name: 'Do Sofá aos 10 km - Hansons',
    nivel: 'iniciante',
    coach: 'Hansons',
    info: 'O plano "Do Sofá aos 10 km da Hansons" é um programa popular para corredores iniciantes que desejam completar sua primeira corrida de 10 km. Este plano de 18 semanas combina caminhada e corrida de forma progressiva, permitindo que o corpo se adapte gradualmente ao exercício. Ideal para quem está começando do zero ou retornando após longo período sem atividade física.',
    path: '10km-couch-iniciante',
    duration: '18 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['10km']
  },
  {
    name: '5 e 10 km Rocha',
    nivel: 'iniciante',
    coach: 'B. Rocha',
    info: 'Prepare-se para suas primeiras provas de 5 e 10 km com o plano do treinador B. Rocha. Este programa de 20 semanas é ideal para iniciantes, combinando corridas fáceis com aumentos graduais de distância. Desenvolva resistência e confiança para enfrentar ambas as distâncias.',
    path: 'corrida-rocha-iniciante',
    duration: '20 semanas',
    activities: ['corrida'],
    img: '/img/pages/shared.jpg',
    isNew: false,
    distances: ['5km', '10km']
  },
  {
    name: '10 km - Hal Higdon',
    nivel: 'intermediário',
    coach: 'Hal Higdon',
    info: 'Este plano de 8 semanas é projetado para corredores intermediários que buscam melhorar seu tempo nos 10 km. Combina corridas fáceis, treinos de ritmo, intervalos e corridas longas progressivas para desenvolver resistência e velocidade. Inclui também treinamento de força para melhorar a economia de corrida e prevenir lesões. Ideal para corredores que já completaram pelo menos uma corrida de 5 km e correm regularmente.',
    path: '10km-halhigdon-intermediario',
    duration: '08 semanas',
    activities: ['corrida', 'força'],
    img: '/img/pages/shared.jpg',
    isNew: true,
    distances: ['5km', '10km'],
    volume: '40'
  },
  {
    name: '10 Km Trail Sarah McCormack',
    nivel: 'intermediário',
    coach: 'Sarah McCormack',
    info: 'Este plano de 10 semanas é projetado para corredores intermediários que já correm pelo menos 4 dias por semana. O programa inclui treinos variados como corridas fáceis, treinos de colina, fartleks e corridas longas para preparar você para uma prova de trail de 10 km. O plano é flexível e pode ser adaptado para 4-6 dias de treino por semana.',
    path: '10km-trail-sarah-mccormack',
    duration: '10 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida', 'trail'],
    isNew: true,
    distances: ['10km'],
    volume: '50'
  },
  {
    name: '5 e 10 km - Faster Road Racing',
    nivel: 'intermediário',
    coach: 'Pete Pfitzinger',
    info: 'Plano de treinamento de 12 semanas para distâncias de 5 km e 10 km, com volume semanal de 50 a 70 km. Desenvolvido por Pete Pfitzinger e Philip Latter, este programa é ideal para corredores intermediários. O plano inclui uma variedade de treinos, como corridas longas, treinos de limiar, intervalados e corridas de ritmo. Baseado no livro Faster Road Racing.',
    path: '10km-frr-intermediario',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['5km', '10km'],
    volume: '70'
  },
  {
    name: '5 e 10 km - Faster Road Racing',
    nivel: 'avançado',
    coach: 'Pete Pfitzinger',
    info: 'Este plano de 12 semanas, desenvolvido por Pete Pfitzinger e Philip Latter, é projetado para corredores avançados que buscam melhorar seu desempenho em provas de 5 km a 10 km. O programa começa com um volume semanal de cerca de 60 km e aumenta gradualmente até cerca de 80 km. Inclui uma variedade de treinos, como corridas longas, treinos de ritmo de limiar, intervalos de VO2 max e corridas de recuperação. Ideal para corredores que já têm uma base sólida e querem levar seu desempenho para o próximo nível.',
    path: '10km-frr-avancado',
    duration: '12 semanas',
    activities: ['corrida'],
    img: '/img/pages/shared.jpg',
    isNew: true,
    distances: ['5km', '10km'],
    volume: '80'
  },
  {
    name: '10 km - Hal Higdon',
    nivel: 'avançado',
    coach: 'Hal Higdon',
    info: 'Leve seu desempenho nos 10 km ao próximo nível com o plano avançado de Hal Higdon. Este programa de 8 semanas é repleto de treinos de qualidade, incluindo intervalos, fartleks e corridas de ritmo. Ideal para corredores experientes buscando tempos competitivos.',
    path: '10km-halhigdon-avancado',
    duration: '08 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida', 'força'],
    isNew: false,
    distances: ['5km', '10km']
  },
  {
    name: '5 e 10 km - Faster Road Racing',
    nivel: 'elite',
    coach: 'Pete Pfitzinger',
    info: 'Este plano de 12 semanas, desenvolvido por Pete Pfitzinger e Philip Latter, é projetado para corredores avançados que buscam melhorar seu desempenho em provas de 5 km até 10 km. O programa começa com um volume semanal de cerca de 80 km e aumenta gradualmente até cerca de 100 km. Inclui uma variedade de treinos, como corridas longas, treinos de ritmo de limiar, intervalos de VO2 max e corridas de recuperação. Ideal para corredores que já têm uma base sólida e querem levar seu desempenho para o próximo nível.',
    path: '10km-frr-elite',
    duration: '12 semanas',
    activities: ['corrida'],
    img: '/img/pages/shared.jpg',
    isNew: true,
    distances: ['5km', '10km', '15km'],
    volume: '100'
  },
  {
    name: '5 e 10 km - Daniels',
    nivel: 'elite',
    coach: 'Jack Daniels',
    info: 'Atinja o ápice do desempenho em 5 e 10 km com o plano de elite de Jack Daniels. Este programa intensivo de 24 semanas é baseado na renomada fórmula VDOT, incorporando treinos altamente específicos e periodização avançada para maximizar velocidade e resistência em ambas as distâncias.',
    path: '5km-jack-daniels-competicao',
    duration: '24 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: false,
    distances: ['5km', '10km']

  },
  // Half Marathon Plans
  {
    name: 'Meia Maratona Daniels',
    nivel: 'iniciante',
    coach: 'Jack Daniels',
    info: 'Prepare-se para sua primeira meia maratona com o plano iniciante de Jack Daniels. Este programa de 24 semanas utiliza a fórmula VDOT para personalizar intensidades, focando no aumento gradual de volume e introduzindo treinos de qualidade. Ideal para corredores Iniciantes na distância.',
    path: 'meia-maratona-jack-daniels-iniciante',
    duration: '24 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: false,
    distances: ['21km']

  },
  {
    name: 'Meia Maratona Hal Higdon Iniciante 1',
    nivel: 'iniciante',
    coach: 'Hal Higdon',
    info: 'Este plano de 12 semanas, desenvolvido pelo renomado treinador Hal Higdon, é ideal para corredores iniciantes que desejam completar sua primeira meia maratona. O programa combina corridas curtas durante a semana, treinos de cross-training e corridas longas progressivas nos fins de semana. Com uma abordagem gradual e equilibrada, este plano prepara o corpo e a mente para o desafio de 21,1 km, priorizando a construção de resistência e prevenção de lesões.',
    path: 'meia-maratona-hal-higdon-iniciante-1',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida', 'força'],
    isNew: true,
    distances: ['21km'],
    volume: '50'
  },
  {
    name: 'Meia Maratona Hal Higdon Iniciante 2',
    nivel: 'iniciante',
    coach: 'Hal Higdon',
    info: 'O Programa de Treinamento para Meia Maratona Iniciante 2 de Hal Higdon é uma progressão do popular plano Iniciante 1. Este programa de 12 semanas é ideal para corredores que já completaram pelo menos uma meia maratona ou que têm uma base sólida de corrida. O plano inclui corridas mais longas durante a semana e um volume total maior em comparação com o Iniciante 1, preparando você para uma performance mais forte na meia maratona.',
    path: 'meia-maratona-hal-higdon-iniciante-2',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida', 'força'],
    isNew: true,
    distances: ['21km'],
    volume: '70'
  },
  {
    name: 'Meia Maratona Hansons',
    nivel: 'iniciante',
    coach: 'Hansons',
    info: 'Aborde sua primeira meia maratona com o método Hansons para iniciantes. Este plano de 18 semanas enfatiza consistência e volume moderado, incorporando o conceito de fadiga cumulativa. Ideal para Iniciantes buscando uma abordagem estruturada e eficaz.',
    path: 'meia-maratona-hansons-iniciante',
    duration: '18 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: false,
  },
  {
    name: 'Meia Maratona Hal Higdon Intermediário 1',
    nivel: 'intermediário',
    coach: 'Hal Higdon',
    info: 'Este plano de 12 semanas, desenvolvido pelo renomado treinador Hal Higdon, é ideal para corredores intermediários que já têm experiência em corridas de distância e buscam melhorar seu desempenho na meia maratona. O programa combina corridas curtas e médias durante a semana, um dia de treinamento cruzado (que adaptaremos para fortalecimento), e corridas longas progressivas nos fins de semana. Também inclui treinos de ritmo e algumas corridas de teste. Com uma abordagem equilibrada, este plano prepara o corpo e a mente para o desafio de 21,1 km, focando no aumento da resistência e na melhoria do ritmo de corrida.',
    path: 'meia-maratona-hal-higdon-intermediario-1',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida', 'força'],
    isNew: true,
    distances: ['21km'],
    volume: '60'
  },
  {
    name: 'Meia Maratona Hal Higdon Intermediário 2',
    nivel: 'intermediário',
    coach: 'Hal Higdon',
    info: 'O plano Intermediário 2 de Hal Higdon para meia maratona é um programa de 12 semanas projetado para corredores com experiência que buscam melhorar seu desempenho. Este plano incorpora uma variedade de treinos, incluindo corridas longas, treinos de ritmo, intervalos e corridas de recuperação. Com um volume semanal que varia de 32 a 56 km, o plano oferece um equilíbrio entre desafio e recuperação, preparando os corredores para uma performance forte no dia da prova.',
    path: 'meia-maratona-hal-higdon-intermediario-2',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida', 'força'],
    isNew: true,
    distances: ['21km'],
    volume: '60'
  },
  {
    name: 'Meia Maratona Pfitzinger',
    nivel: 'intermediário',
    coach: 'Pete Pfitzinger',
    info: 'Prepare-se para sua melhor meia maratona com este plano de 12 semanas desenvolvido por Pete Pfitzinger e Philip Latter. Com um volume semanal de 47 a 75 km, este programa é ideal para corredores intermediários que buscam elevar seu desempenho. Combinando corridas longas, treinos de ritmo de limiar, intervalos e corridas de ritmo, este plano vai desafiar e transformar sua corrida. Lembre-se, cada passo deste plano te aproxima da sua melhor versão como corredor. Acredite no processo, confie no seu treinamento, e prepare-se para surpreender a si mesmo no dia da prova!',
    path: 'meia-maratona-pfitzinger-latter-intermediario',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['21km'],
    volume: '75'
  },
  {
    name: 'Meia Maratona Nike',
    nivel: 'intermediário',
    coach: 'Chris Bennett',
    info: 'Prepare-se para uma meia maratona com o plano flexível da Nike, desenvolvido por Chris Bennett. Este programa de 14 semanas adapta-se ao seu nível, combinando corridas fáceis, longas e treinos de ritmo. Ideal para corredores intermediários buscando melhorar seu tempo.',
    path: 'meia-maratona-nike-iniciante',
    duration: '14 semanas',
    img: '/img/planos/hmnike.jpg',
    activities: ['corrida'],
    isNew: false,
    distances: ['21km']
  },
  {
    name: 'Meia Maratona Santana',
    nivel: 'intermediário',
    coach: 'Abner Santana',
    info: 'Aprimore seu desempenho na meia maratona com o plano de Abner Santana. Este programa de 12 semanas é baseado em experiências práticas, focando em progressão de volume e intensidade. Ideal para corredores intermediários visando melhorar tempos e estratégias de corrida.',
    path: 'meia-maratona-santana-intermediario',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: false,
    distances: ['21km']
  },
  {
    name: 'Meia Maratona Daniels',
    nivel: 'intermediário',
    coach: 'Jack Daniels',
    info: 'Eleve seu desempenho na meia maratona com o plano intermediário de Jack Daniels. Este programa de 24 semanas utiliza a fórmula VDOT para otimizar intensidades, incorporando uma variedade de treinos de qualidade. Ideal para corredores buscando melhorar significativamente seus tempos.',
    path: 'meia-maratona-jack-daniels-intermedario',
    duration: '24 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: false,
    distances: ['21km']
  },
  {
    name: 'Meia Maratona Daniels',
    nivel: 'avançado',
    coach: 'Jack Daniels',
    info: 'Alcance seu potencial máximo na meia maratona com o plano avançado de Jack Daniels. Este programa exigente de 24 semanas utiliza a fórmula VDOT para prescrever treinos de alta intensidade e volume. Projetado para corredores experientes visando tempos competitivos.',
    path: 'meia-maratona-jack-daniels-avancado',
    duration: '24 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: false,
  },
  {
    name: 'Meia Maratona Hansons',
    nivel: 'avançado',
    coach: 'Hansons',
    info: 'Este plano avançado de 18 semanas da Hansons Coaching Services é projetado para corredores experientes visando melhorar seu desempenho na meia maratona. O programa enfatiza a fadiga cumulativa e inclui uma variedade de treinos, incluindo intervalos, ritmo de meia maratona e corridas longas progressivas. Ideal para corredores que buscam um desafio e estão dispostos a dedicar tempo significativo ao treinamento.',
    path: 'meia-maratona-hansons-avancado',
    duration: '18 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['21km'],
    volume: '80'
  },
  {
    name: 'Meia Maratona Pfitzinger',
    nivel: 'avançado',
    coach: 'Pete Pfitzinger',
    info: 'Eleve seu desempenho na meia maratona com o plano de 12 semanas de Pete Pfitzinger e Philip Latter! Projetado para corredores intermediários que buscam desafios, este programa inspirador te levará de 75 a 100 km por semana. Baseado no best-seller "Faster Road Racing: 5K to Half Marathon", este plano combina ciência e experiência prática para otimizar seu treinamento. Prepare-se para corridas longas revigorantes, treinos de ritmo desafiadores e intervalos que testarão seus limites. Com uma progressão cuidadosamente estruturada, você chegará à linha de largada mais forte, mais rápido e confiante do que nunca. Está pronto para transformar seu potencial em realidade? Seu novo recorde pessoal começa aqui!', path: 'meia-maratona-pfitzinger-latter-avancado',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['21km'],
    volume: '100'
  },
  {
    name: 'Meia Maratona Trail Sarah McCormack',
    nivel: 'avançado',
    coach: 'Sarah McCormack',
    info: 'Este plano de 10 semanas para meia maratona em trilha é desenvolvido por Sarah McCormack. É projetado para corredores avançados que já correm 5-6 dias por semana, acumulando uma quilometragem semanal média de 45-65 km. O plano inclui uma variedade de treinos, incluindo repetições em ladeira, corridas de ritmo, fartlek e corridas longas. É altamente recomendado consultar um médico antes de iniciar este programa, especialmente se você é novo na corrida ou não passou por uma avaliação recentemente.',
    path: 'meia-maratona-trail-sarah-mccormack',
    duration: '10 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida', 'trail'],
    isNew: true,
    distances: ['21km'],
    volume: '65'
  },
  {
    name: 'Meia Maratona Daniels',
    nivel: 'elite',
    coach: 'Jack Daniels',
    info: 'Atinja o ápice do desempenho na meia maratona com o plano de elite de Jack Daniels. Este programa intensivo de 24 semanas é meticulosamente estruturado, utilizando a fórmula VDOT para maximizar cada aspecto do treinamento. Projetado para corredores de alto nível visando tempos excepcionais.',
    path: 'meia-maratona-jack-daniels-elite',
    duration: '24 semanas',
    img: '/img/planos/hmjdelite.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['21km']
  },

  // Marathon Plans
  {
    name: 'Maratona Hal Higdon iniciante 1',
    nivel: 'iniciante',
    coach: 'Hal Higdon',
    info: 'Este é o programa mais popular de Hal: o Programa de Treinamento para Maratona Iniciante 1. Se você está treinando para sua primeira maratona, este é o programa de treinamento ideal! Mesmo se você for um maratonista experiente, pode escolher esta abordagem suave e de baixa quilometragem para seu esporte favorito. Mais de um milhão de corredores usaram os programas de Hal com sucesso. O Iniciante 1 vai levá-lo à linha de partida - e à linha de chegada.',
    path: 'maratona-hal-higdon-iniciante',
    duration: '18 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: false,
    distances: ['42km']
  },
  {
    name: 'Maratona Hal Higdon iniciante 2',
    nivel: 'iniciante',
    coach: 'Hal Higdon',
    info: 'O Programa de Treinamento para Maratona Iniciante 2 de Hal Higdon é uma progressão do popular plano Iniciante 1. Este programa de 18 semanas é ideal para corredores que já completaram pelo menos uma maratona ou que têm uma base sólida de corrida. O plano inclui corridas mais longas durante a semana e um volume total maior em comparação com o Iniciante 1, preparando você para uma performance mais forte na maratona.',
    path: 'maratona-hal-higdon-iniciante-2',
    duration: '18 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['42km'],
    volume: '60'
  },
  {
    name: 'Maratona Hansons',
    nivel: 'intermediário',
    coach: 'Hansons',
    info: 'Prepare-se para sua primeira maratona com o método Hansons para iniciantes. Este plano de 18 semanas enfatiza consistência e volume moderado, incorporando o conceito de fadiga cumulativa. Ideal para Iniciantes buscando uma abordagem estruturada e eficaz.',
    path: 'maratona-hansons-intermedario',
    duration: '18 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['42km'],
    volume: '80'
  },
  {
    name: 'Maratona Hansons',
    nivel: 'avançado',
    coach: 'Hansons',
    info: 'Plano de 18 semanas para maratona, desenvolvido pelos irmãos Hanson. Este programa é ideal para corredores avançados buscando melhorar seu tempo na maratona. Inclui uma variedade de treinos, incluindo corridas longas, treinos de ritmo de maratona, intervalos e corridas de resistência. O plano se baseia no princípio da fadiga acumulada para simular as últimas milhas de uma maratona.',
    path: 'maratona-hansons-avancado',
    duration: '18 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['42km'],
    volume: '110'
  },
  {
    name: 'Maratona Pfitzinger/Douglas 90km',
    nivel: 'avançado',
    coach: 'Pete Pfitzinger',
    info: 'Plano de 12 semanas para maratona, com volume semanal de até 90 km. Desenvolvido por Pete Pfitzinger e Scott Douglas, este programa é ideal para corredores avançados buscando melhorar seu tempo na maratona. Inclui uma variedade de treinos, incluindo corridas longas, treinos de ritmo de maratona, intervalos e corridas de limiar. Plano do livro: Advanced Marathoning.',
    path: 'maratona-pfitzinger-douglas-avancado-90km',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['42km'],
    volume: '90'
  },
  {
    name: 'Maratona Pfitzinger/Douglas 115km',
    nivel: 'avançado',
    coach: 'Pete Pfitzinger',
    info: 'Plano de 12 semanas para maratona, com volume semanal de até  115km. Desenvolvido por Pete Pfitzinger e Scott Douglas, este programa é ideal para corredores avançados buscando melhorar seu tempo na maratona. Inclui uma variedade de treinos, incluindo corridas longas, treinos de ritmo de maratona, intervalos e corridas de limiar. Plano do livro: Advanced Marathoning.',
    path: 'maratona-pfitzinger-douglas-avancado-115km',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['42km'],
    volume: '115'
  },
  {
    name: 'Maratona Pfitzinger/Douglas 90km',
    nivel: 'avançado',
    coach: 'Pete Pfitzinger',
    info: 'Plano de 18 semanas para maratona, com volume semanal de até 90 km. Desenvolvido por Pete Pfitzinger e Scott Douglas, este programa é ideal para corredores avançados buscando melhorar seu tempo na maratona. Inclui uma variedade de treinos, incluindo corridas longas, treinos de ritmo de maratona, intervalos e corridas de limiar. Plano do livro: Advanced Marathoning.',
    path: 'maratona-pfitzinger-douglas-avancado-90km-18sem',
    duration: '18 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['42km'],
    volume: '90'
  },
  {
    name: 'Maratona Pfitzinger/Douglas 120km',
    nivel: 'avançado',
    coach: 'Pete Pfitzinger',
    info: 'Plano de 18 semanas para maratona, com volume semanal de 88 a 115 km. Desenvolvido por Pete Pfitzinger e Scott Douglas, este programa é ideal para corredores avançados buscando melhorar seu tempo na maratona. Inclui uma variedade de treinos, incluindo corridas longas, treinos de ritmo de maratona, intervalos e corridas de limiar. Plano do livro: Advanced Marathoning.',
    path: 'maratona-pfitzinger-douglas-avancado-120km-18sem',
    duration: '18 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['42km'],
    volume: '120'
  },
  {
    name: 'Maratona Daniels',
    nivel: 'avançado',
    coach: 'Jack Daniels',
    info: 'Prepare-se para uma maratona de alto nível com o plano avançado de Jack Daniels. Este programa de 24 semanas é baseado na renomada fórmula VDOT, incorporando uma progressão cuidadosa de volume e intensidade. Ideal para corredores experientes visando melhorar significativamente seus tempos na maratona ou encarar a maratona depois de uma base sólida em meia maratonas.',
    path: 'maratona-jack-daniels-avancado',
    duration: '24 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['42km'],
    trainingPeaksUrl: 'https://www.trainingpeaks.com/training-plans/running/marathon/tp-527128/maratona-santana-avancada',
    videoUrl: 'https://youtu.be/0fI9ZXLAc48'
  },
  {
    name: 'Maratona Trail Sarah McCormack',
    nivel: 'avançado',
    coach: 'Sarah McCormack',
    info: 'Este plano de 16 semanas é projetado para corredores avançados que se preparam para uma maratona de trail. Ideal para atletas que já correm 5-6 dias por semana, acumulando uma quilometragem semanal média de pelo menos 65-80 km. O programa combina corridas longas progressivas, treinos de colina, fartleks e corridas em ritmo de prova para desenvolver força, resistência e habilidades específicas para trilhas. O plano é flexível e pode ser modificado para 5 dias de corrida por semana, omitindo as corridas fáceis de sábado ou quinta-feira. Inclui orientações detalhadas sobre como adaptar o plano às suas necessidades e nível de condicionamento atual.',
    path: 'maratona-trail-sarah-mccormack',
    duration: '16 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida', 'trail'],
    isNew: true,
    distances: ['42km'],
    volume: '80',
  },
  {
    name: 'Maratona Santana',
    nivel: 'elite',
    coach: 'Abner Santana',
    info: 'Prepare-se para uma performance de elite na maratona com o plano de Abner Santana. Baseado na metodologia de Jack Daniels, este programa de 24 semanas é altamente estruturado, incorporando treinos de alta qualidade e volume substancial. Projetado para corredores de alto nível visando tempos competitivos.',
    path: 'maratona-santana-elite',
    duration: '24 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['42km']
  },
  {
    name: 'Maratona Pfitzinger/Douglas 140km',
    nivel: 'elite',
    coach: 'Pete Pfitzinger',
    info: 'Plano de 12 semanas para maratona, com volume semanal de até  140 km. Desenvolvido por Pete Pfitzinger e Scott Douglas, este programa é ideal para corredores avançados buscando melhorar seu tempo na maratona. Inclui uma variedade de treinos, incluindo corridas longas, treinos de ritmo de maratona, intervalos e corridas de limiar. Plano do livro: Advanced Marathoning.',
    path: 'maratona-pfitzinger-douglas-avancado-140km',
    duration: '12 semanas',
    img: '/img/pages/shared.jpg',
    activities: ['corrida'],
    isNew: true,
    distances: ['42km'],
    volume: '140'
  },
  // Other Plans
  {
    name: 'Ultramaratona 50 Milhas - Sarah McCormack',
    nivel: 'iniciante',
    coach: 'Sarah McCormack',
    info: 'Este plano de 16 semanas foi desenvolvido pela ultramaratonista internacional e treinadora Sarah McCormack para preparar corredores iniciantes para sua primeira ultramaratona de 50 milhas (80 km). Adequado para corredores que já completaram pelo menos uma maratona de trilha ou que têm experiência em corridas de longa distância. O plano inclui uma combinação de corridas fáceis, treinos de colina, corridas longas progressivas e caminhadas longas em terreno montanhoso para simular as condições da prova.',
    path: 'ultra-sarah-mccormack-iniciante',
    duration: '16 semanas',
    activities: ['corrida', 'ultra', 'trail'],
    img: '/img/pages/shared.jpg',
    isNew: true,
    distances: ['80km'],
    volume: '80'
  },
  {
    name: 'Ultramaratona 50 Milhas - Sarah McCormack',
    nivel: 'avançado',
    coach: 'Sarah McCormack',
    info: 'Este plano de treinamento de 16 semanas é projetado para corredores avançados que desejam completar uma ultramaratona de 50 milhas (80 km). O programa inclui uma combinação de corridas longas, treinos de ritmo, intervalos, e treinamento específico em colinas para preparar o corpo e a mente para o desafio de uma ultramaratona. O plano também incorpora caminhadas longas em terreno montanhoso, essenciais para o sucesso em ultramaratonas. Com um aumento gradual no volume e intensidade, seguido por um período de taper adequado, este plano visa levar o corredor ao pico de forma no dia da prova.',
    path: 'ultra-sarah-mccormack-avancado',
    duration: '16 semanas',
    activities: ['corrida', 'ultra', 'trail'],
    img: '/img/pages/shared.jpg',
    isNew: true,
    distances: ['80km'],
    volume: '120'
  },
  {
    name: 'Master: +50 anos',
    nivel: 'intermediário',
    coach: 'Jack Daniels',
    info: 'Mantenha-se forte e competitivo após os 50 com o plano Master de Jack Daniels. Este programa de 12 semanas é adaptado para corredores maduros, focando em volume adequado e recuperação otimizada. Ideal para quem busca manter o condicionamento e melhorar o desempenho de forma segura.',
    path: 'jack-daniels-master',
    duration: '12 semanas',
    img: '/img/planos/masterrunners.jpg',
    activities: ['corrida'],
    isNew: false,
    distances: ['5km', '10km'],
  },
];

export default plans;